 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
   webplantilla/webplantilla-main:
     build: ./webplantilla/webplantilla-main:
     ports:
       - 8081:80
